<!DOCTYPE html>
<html>
        <head> 
        <!-- 練習文章 -->
                <meta charset="UTF-8">
                <title>庫巴大爺的網頁</title>
                <link rel="stylesheet" href="index_html_style.css">
                <style>
                        .prestyle{color: black;font-size: large;font-family: 標楷體;
                                
                        }
                </style>
        </head>
        <body>
           <h1><a name="menu"></a>庫巴大爺最讚!!!!!!!!!</h1> 
           <h3>主頁</h3>
           <a href="index2.html">第二章</a>
           <a href="index3.html">第三章</a>
           <a href="8888.html">8888</a>
           <a href="practice.html">practive1</a>
           <a href="index5.html">index5</a>
           <br/>
           <hr>
           <i><h2><p style="color: red;">讚!</p></p></i></h2></p></i>
           <br>
           <hr/>
           <h2>連結</h2>
           <a href="https://www.youtube.com/watch?v=CLUPkcLQm64&ab_channel=GrandmaCan-%E6%88%91%E9%98%BF%E5%AC%A4%E9%83%BD%E6%9C%83">【html】1小時初學者教學 #html #html教學 #html入門</a>
        <br/>
        <a href="https://www.youtube.com/watch?v=Ml78vnNTBLw">【css】2小時初學者教學 #css #css教學 #css入門</a>
        <br/>
        <a href="https://www.w3schools.com/html/" target="_blank"><img src="https://www.zeldadungeon.net/wiki/images/f/fd/Link.png" width="200"></a>
        <h3>林克:點我看進階教學</h3>
        <br/>
           <img src="779694-PH (1).jpg" width="400" /> 
        <br/>
        <br/>
        <br/>   
          
        "<iframe width="560" height="315" src="https://www.youtube.com/embed/CLUPkcLQm64" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>">
        <ol type="1">
        <br>
        <video  src="yt1s.com - Nintendo みまもり Switch 紹介映像.mp4" controls width="500" >影片無法撥放</video>
        <br>
        <li><h2>庫巴</h2></li> <li><b>成績</b></li>
                <table width="400"  style="border: 1px double black;">
                <tr >
                   <td   style="border: 1px solid black;">Bowser</td>   <td  style="border: 1px solid black;">Bowser jr</td>
                </tr>
                <tr  >
                        <td style="border: 1px solid black;">100</td> <td style="border: 1px solid black;">88</td>
                </tr>
                </table>
        <dl> 
                <dt>Bowser</dt>
                <dd>bowser is a good animal, because it can bite you.(???)</dd>
        </dl>
        <hr>
        <br>
        <pre class="prestyle">
                    
                <!--在此輸入標籤(帳密)-->
                <br>                <hr>     <br>
                <input type="text"placeholder="請輸入帳號" />
                <br>
                <br>
                <input type="password" placeholder="請輸入密碼" />
                <br/>
                <br/>
                <textarea>  </textarea>
                <br><br><br><br><br>
                <a href="#menu">回最上面</a>
                <br><br><br><br><br>
                <a href="mailto:LeoChiuBowser@gmail.com?Subject=給Bowser建議">給Bowser建議</a>
        </pre>
       </body>
</html>
